/**
 * Supabase Generated Types
 *
 * This file is auto-generated by running:
 *   supabase gen types typescript --local > web/types/supabase.ts
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Re-run the generation command after any database schema changes.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string | null;
          full_name: string | null;
          avatar_url: string | null;
          updated_at: string | null;
          created_at: string | null;
        };
        Insert: {
          id: string;
          email?: string | null;
          full_name?: string | null;
          avatar_url?: string | null;
          updated_at?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string | null;
          full_name?: string | null;
          avatar_url?: string | null;
          updated_at?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      partnerships: {
        Row: {
          id: string;
          user_id_1: string;
          user_id_2: string;
          status: string;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          user_id_1: string;
          user_id_2: string;
          status?: string;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id_1?: string;
          user_id_2?: string;
          status?: string;
          created_at?: string | null;
        };
        Relationships: [];
      };
      tasks: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          status: string | null;
          priority: string | null;
          due_date: string | null;
          reminder_time: string | null;
          subtasks: Json | null;
          tags: string[] | null;
          type: string | null;
          duration: number | null;
          location: string | null;
          dependency_ids: string[] | null;
          is_shared: boolean | null;
          recurrence: Json | null;
          next_recurrence_date: string | null;
          created_at: string | null;
          notification_enabled: boolean | null;
          notification_minutes_before: number | null;
          notification_time: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          description?: string | null;
          status?: string | null;
          priority?: string | null;
          due_date?: string | null;
          reminder_time?: string | null;
          subtasks?: Json | null;
          tags?: string[] | null;
          type?: string | null;
          duration?: number | null;
          location?: string | null;
          dependency_ids?: string[] | null;
          is_shared?: boolean | null;
          recurrence?: Json | null;
          next_recurrence_date?: string | null;
          created_at?: string | null;
          notification_enabled?: boolean | null;
          notification_minutes_before?: number | null;
          notification_time?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          description?: string | null;
          status?: string | null;
          priority?: string | null;
          due_date?: string | null;
          reminder_time?: string | null;
          subtasks?: Json | null;
          tags?: string[] | null;
          type?: string | null;
          duration?: number | null;
          location?: string | null;
          dependency_ids?: string[] | null;
          is_shared?: boolean | null;
          recurrence?: Json | null;
          next_recurrence_date?: string | null;
          created_at?: string | null;
          notification_enabled?: boolean | null;
          notification_minutes_before?: number | null;
          notification_time?: string | null;
        };
        Relationships: [];
      };
      transactions: {
        Row: {
          id: string;
          user_id: string;
          description: string;
          amount: number;
          type: string;
          date: string | null;
          frequency: string | null;
          next_due_date: string | null;
          created_at: string | null;
          category: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          description: string;
          amount: number;
          type: string;
          date?: string | null;
          frequency?: string | null;
          next_due_date?: string | null;
          created_at?: string | null;
          category?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          description?: string;
          amount?: number;
          type?: string;
          date?: string | null;
          frequency?: string | null;
          next_due_date?: string | null;
          created_at?: string | null;
          category?: string | null;
        };
        Relationships: [];
      };
      user_settings: {
        Row: {
          user_id: string;
          budget_limit: number | null;
          budget_duration: string | null;
          savings: number | null;
          display_name: string | null;
          theme: string | null;
          updated_at: string | null;
        };
        Insert: {
          user_id: string;
          budget_limit?: number | null;
          budget_duration?: string | null;
          savings?: number | null;
          display_name?: string | null;
          theme?: string | null;
          updated_at?: string | null;
        };
        Update: {
          user_id?: string;
          budget_limit?: number | null;
          budget_duration?: string | null;
          savings?: number | null;
          display_name?: string | null;
          theme?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      notes: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          content: string;
          is_checklist: boolean | null;
          checklist_items: Json | null;
          is_shared: boolean | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          content?: string;
          is_checklist?: boolean | null;
          checklist_items?: Json | null;
          is_shared?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          content?: string;
          is_checklist?: boolean | null;
          checklist_items?: Json | null;
          is_shared?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      note_shares: {
        Row: {
          id: string;
          note_id: string;
          owner_id: string;
          shared_with_id: string;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          note_id: string;
          owner_id: string;
          shared_with_id: string;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          note_id?: string;
          owner_id?: string;
          shared_with_id?: string;
          created_at?: string | null;
        };
        Relationships: [];
      };
      routines: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string | null;
          pattern: Json;
          time: string | null;
          duration: number | null;
          is_active: boolean | null;
          notification_enabled: boolean | null;
          notification_minutes_before: number | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string | null;
          pattern: Json;
          time?: string | null;
          duration?: number | null;
          is_active?: boolean | null;
          notification_enabled?: boolean | null;
          notification_minutes_before?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          description?: string | null;
          pattern?: Json;
          time?: string | null;
          duration?: number | null;
          is_active?: boolean | null;
          notification_enabled?: boolean | null;
          notification_minutes_before?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      budget_shares: {
        Row: {
          id: string;
          owner_id: string;
          partner_id: string;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          owner_id: string;
          partner_id: string;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          owner_id?: string;
          partner_id?: string;
          created_at?: string | null;
        };
        Relationships: [];
      };
      push_subscriptions: {
        Row: {
          id: string;
          user_id: string;
          subscription: Json;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          subscription: Json;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          subscription?: Json;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      scheduled_notifications: {
        Row: {
          id: string;
          user_id: string;
          task_id: string | null;
          title: string;
          body: string | null;
          scheduled_at: string;
          sent: boolean | null;
          sent_at: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          task_id?: string | null;
          title: string;
          body?: string | null;
          scheduled_at: string;
          sent?: boolean | null;
          sent_at?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          task_id?: string | null;
          title?: string;
          body?: string | null;
          scheduled_at?: string;
          sent?: boolean | null;
          sent_at?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      account_deletion_requests: {
        Row: {
          id: string;
          user_id: string;
          token: string;
          email: string;
          requested_at: string | null;
          expires_at: string;
          confirmed_at: string | null;
          status: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          token: string;
          email: string;
          requested_at?: string | null;
          expires_at: string;
          confirmed_at?: string | null;
          status?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          token?: string;
          email?: string;
          requested_at?: string | null;
          expires_at?: string;
          confirmed_at?: string | null;
          status?: string | null;
        };
        Relationships: [];
      };
      teams: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          description: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          owner_id: string;
          name: string;
          description?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          owner_id?: string;
          name?: string;
          description?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      team_members: {
        Row: {
          id: string;
          team_id: string;
          user_id: string;
          role: string;
          status: string;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          team_id: string;
          user_id: string;
          role?: string;
          status?: string;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          team_id?: string;
          user_id?: string;
          role?: string;
          status?: string;
          created_at?: string | null;
        };
        Relationships: [];
      };
      day_plans: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          task_ids: string[] | null;
          links: Json | null;
          layout: Json | null;
          template_id: string | null;
          is_recurring: boolean | null;
          recurring_config: Json | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          task_ids?: string[] | null;
          links?: Json | null;
          layout?: Json | null;
          template_id?: string | null;
          is_recurring?: boolean | null;
          recurring_config?: Json | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          task_ids?: string[] | null;
          links?: Json | null;
          layout?: Json | null;
          template_id?: string | null;
          is_recurring?: boolean | null;
          recurring_config?: Json | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      rate_limits: {
        Row: {
          id: string;
          key: string;
          count: number;
          window_start: string;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          key: string;
          count?: number;
          window_start?: string;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          key?: string;
          count?: number;
          window_start?: string;
          created_at?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      get_user_partners: {
        Args: {
          user_uuid: string;
        };
        Returns: string[];
      };
      is_team_owner: {
        Args: {
          p_team_id: string;
          p_user_id: string;
        };
        Returns: boolean;
      };
      is_team_member: {
        Args: {
          p_team_id: string;
          p_user_id: string;
        };
        Returns: boolean;
      };
      is_team_admin: {
        Args: {
          p_team_id: string;
          p_user_id: string;
        };
        Returns: boolean;
      };
      cleanup_rate_limits: {
        Args: Record<string, never>;
        Returns: undefined;
      };
      increment_rate_limit: {
        Args: {
          p_key: string;
          p_window_duration_seconds: number;
        };
        Returns: number;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

// Convenience type aliases
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
